"""initial schema

Revision ID: 6b6dee7c951f
Revises: 
Create Date: 2025-10-29 20:45:47.116857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b6dee7c951f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('code', name='uq_feature_code')
    )
    op.create_table('npa_act',
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('edition', sa.String(length=128), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tenant',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('slug', name='uq_tenant_slug')
    )
    op.create_table('api_key',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key_prefix', sa.String(length=32), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('scopes', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_prefix'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_api_key_tenant_name')
    )
    op.create_index(op.f('ix_api_key_tenant_id'), 'api_key', ['tenant_id'], unique=False)
    op.create_table('asset',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_tenant_id'), 'asset', ['tenant_id'], unique=False)
    op.create_table('checklist',
    sa.Column('npa_code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'npa_code', 'version', name='uq_checklist_tenant_code_version')
    )
    op.create_index('ix_checklist_created_at', 'checklist', ['created_at'], unique=False)
    op.create_index('ix_checklist_npa_code', 'checklist', ['tenant_id', 'npa_code'], unique=False)
    op.create_index(op.f('ix_checklist_tenant_id'), 'checklist', ['tenant_id'], unique=False)
    op.create_index('ix_checklist_title', 'checklist', ['tenant_id', 'title'], unique=False)
    op.create_table('company',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_company_tenant_name')
    )
    op.create_index(op.f('ix_company_tenant_id'), 'company', ['tenant_id'], unique=False)
    op.create_table('document_pack',
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_document_pack_code')
    )
    op.create_index(op.f('ix_document_pack_tenant_id'), 'document_pack', ['tenant_id'], unique=False)
    op.create_table('featureenablement',
    sa.Column('feature_id', sa.String(length=36), nullable=False),
    sa.Column('on', sa.Boolean(), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['feature.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'feature_id', name='uq_feature_enablement_tenant_feature')
    )
    op.create_index('ix_feature_enablement_feature_id', 'featureenablement', ['feature_id'], unique=False)
    op.create_index('ix_feature_enablement_on', 'featureenablement', ['on'], unique=False)
    op.create_index(op.f('ix_featureenablement_tenant_id'), 'featureenablement', ['tenant_id'], unique=False)
    op.create_table('file',
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('mime', sa.String(length=128), nullable=False),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_file_sha256', 'file', ['tenant_id', 'sha256'], unique=False)
    op.create_index('ix_file_storage_key', 'file', ['tenant_id', 'storage_key'], unique=True)
    op.create_index(op.f('ix_file_tenant_id'), 'file', ['tenant_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', name='idempotencystatus'), nullable=False),
    sa.Column('request_hash', sa.String(length=128), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'endpoint', 'key', name='uq_idempotency_keys')
    )
    op.create_index('ix_idempotency_keys_lookup', 'idempotency_keys', ['tenant_id', 'endpoint', 'key'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_tenant_id'), 'idempotency_keys', ['tenant_id'], unique=False)
    op.create_table('incident',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='incidentseverity'), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_tenant_id'), 'incident', ['tenant_id'], unique=False)
    op.create_table('journalentry',
    sa.Column('entry_type', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journalentry_tenant_id'), 'journalentry', ['tenant_id'], unique=False)
    op.create_table('npa',
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('edition_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'OBSOLETE', name='npastatus'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_npa_code')
    )
    op.create_index(op.f('ix_npa_tenant_id'), 'npa', ['tenant_id'], unique=False)
    op.create_table('npa_clause',
    sa.Column('act_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['act_id'], ['npa_act.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('act_id', 'code', name='uq_npa_clause_code_per_act')
    )
    op.create_index(op.f('ix_npa_clause_act_id'), 'npa_clause', ['act_id'], unique=False)
    op.create_table('outbox',
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_tenant_id'), 'outbox', ['tenant_id'], unique=False)
    op.create_table('packageprofile',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_package_profile_name')
    )
    op.create_index(op.f('ix_packageprofile_tenant_id'), 'packageprofile', ['tenant_id'], unique=False)
    op.create_table('plantask',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'DONE', 'CANCELLED', name='plantaskstatus'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plantask_tenant_id'), 'plantask', ['tenant_id'], unique=False)
    op.create_table('risk_controls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_control_tenant_code', 'risk_controls', ['tenant_id', 'code'], unique=True)
    op.create_index(op.f('ix_risk_controls_tenant_id'), 'risk_controls', ['tenant_id'], unique=False)
    op.create_table('risk_hazards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('module', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_hazard_tenant_code', 'risk_hazards', ['tenant_id', 'code'], unique=True)
    op.create_index(op.f('ix_risk_hazards_tenant_id'), 'risk_hazards', ['tenant_id'], unique=False)
    op.create_table('risk_matrix',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('likelihood', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('band', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'severity', 'likelihood', name='uq_risk_matrix_cell')
    )
    op.create_index(op.f('ix_risk_matrix_tenant_id'), 'risk_matrix', ['tenant_id'], unique=False)
    op.create_table('riskmethodology',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_risk_methodology_name')
    )
    op.create_index(op.f('ix_riskmethodology_tenant_id'), 'riskmethodology', ['tenant_id'], unique=False)
    op.create_table('template',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_templates_tenant_name')
    )
    op.create_index(op.f('ix_template_name'), 'template', ['name'], unique=False)
    op.create_index(op.f('ix_template_storage_key'), 'template', ['storage_key'], unique=False)
    op.create_index(op.f('ix_template_tenant_id'), 'template', ['tenant_id'], unique=False)
    op.create_table('user',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'OT_SPECIALIST', 'METHODIST', 'MANAGER', 'EXECUTOR', 'CLERK', 'CLIENT', 'AUDITOR', 'TEACHER', 'STUDENT', name='roleenum'), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_email', 'user', ['tenant_id', 'email'], unique=True)
    op.create_index(op.f('ix_user_tenant_id'), 'user', ['tenant_id'], unique=False)
    op.create_table('warehouseppe',
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouseppe_tenant_id'), 'warehouseppe', ['tenant_id'], unique=False)
    op.create_table('auditlog',
    sa.Column('when', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=128), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auditlog_action', 'auditlog', ['action'], unique=False)
    op.create_index('ix_auditlog_object', 'auditlog', ['object_type', 'object_id'], unique=False)
    op.create_index('ix_auditlog_when', 'auditlog', ['when'], unique=False)
    op.create_index(op.f('ix_auditlog_tenant_id'), 'auditlog', ['tenant_id'], unique=False)
    op.create_table('document_pack_item',
    sa.Column('pack_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pack_id'], ['document_pack.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_pack_item_pack_id'), 'document_pack_item', ['pack_id'], unique=False)
    op.create_index(op.f('ix_document_pack_item_template_id'), 'document_pack_item', ['template_id'], unique=False)
    op.create_index(op.f('ix_document_pack_item_tenant_id'), 'document_pack_item', ['tenant_id'], unique=False)
    op.create_table('equipment',
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'IN_SERVICE', 'DECOMMISSIONED', name='equipmentstatus'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_asset_id'), 'equipment', ['asset_id'], unique=False)
    op.create_index(op.f('ix_equipment_tenant_id'), 'equipment', ['tenant_id'], unique=False)
    op.create_table('packagepreset',
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['packageprofile.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packagepreset_profile_id'), 'packagepreset', ['profile_id'], unique=False)
    op.create_index(op.f('ix_packagepreset_tenant_id'), 'packagepreset', ['tenant_id'], unique=False)
    op.create_table('position',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'company_id', 'name', name='uq_position_company_name')
    )
    op.create_index(op.f('ix_position_company_id'), 'position', ['company_id'], unique=False)
    op.create_index(op.f('ix_position_tenant_id'), 'position', ['tenant_id'], unique=False)
    op.create_table('riskmap',
    sa.Column('methodology_id', sa.String(), nullable=False),
    sa.Column('matrix', sa.JSON(), nullable=False),
    sa.Column('recalculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['methodology_id'], ['riskmethodology.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_riskmap_methodology_id'), 'riskmap', ['methodology_id'], unique=False)
    op.create_index(op.f('ix_riskmap_tenant_id'), 'riskmap', ['tenant_id'], unique=False)
    op.create_table('site',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_company_id'), 'site', ['company_id'], unique=False)
    op.create_index(op.f('ix_site_tenant_id'), 'site', ['tenant_id'], unique=False)
    op.create_table('templateversion',
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.LargeBinary(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='templateversionstatus'), nullable=False),
    sa.Column('payload_key', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'version', name='uq_template_version')
    )
    op.create_index(op.f('ix_templateversion_template_id'), 'templateversion', ['template_id'], unique=False)
    op.create_index(op.f('ix_templateversion_tenant_id'), 'templateversion', ['tenant_id'], unique=False)
    op.create_table('inspection',
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('checklist_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='inspectionstatus'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklist.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inspection_checklist_id', 'inspection', ['checklist_id'], unique=False)
    op.create_index('ix_inspection_site_id', 'inspection', ['site_id'], unique=False)
    op.create_index('ix_inspection_started_at', 'inspection', ['started_at'], unique=False)
    op.create_index('ix_inspection_status', 'inspection', ['status'], unique=False)
    op.create_index(op.f('ix_inspection_tenant_id'), 'inspection', ['tenant_id'], unique=False)
    op.create_table('npabinding',
    sa.Column('template_version_id', sa.String(), nullable=False),
    sa.Column('npa_id', sa.String(), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['npa_id'], ['npa.id'], ),
    sa.ForeignKeyConstraint(['template_version_id'], ['templateversion.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_npabinding_npa_id'), 'npabinding', ['npa_id'], unique=False)
    op.create_index(op.f('ix_npabinding_template_version_id'), 'npabinding', ['template_version_id'], unique=False)
    op.create_index(op.f('ix_npabinding_tenant_id'), 'npabinding', ['tenant_id'], unique=False)
    op.create_table('person',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_company_id'), 'person', ['company_id'], unique=False)
    op.create_index(op.f('ix_person_tenant_id'), 'person', ['tenant_id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('template_version_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'DONE', 'ERROR', name='pipelinerunstatus'), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('outputs', sa.JSON(), nullable=True),
    sa.Column('result_metadata', sa.JSON(), nullable=False),
    sa.Column('docx_storage_key', sa.String(length=512), nullable=True),
    sa.Column('pdf_storage_key', sa.String(length=512), nullable=True),
    sa.Column('result_s3_key', sa.String(length=512), nullable=True),
    sa.Column('error', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.ForeignKeyConstraint(['template_version_id'], ['templateversion.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_idempotency_key'), 'pipeline_runs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_template_id'), 'pipeline_runs', ['template_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_template_version_id'), 'pipeline_runs', ['template_version_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_tenant_id'), 'pipeline_runs', ['tenant_id'], unique=False)
    op.create_index('ix_pipeline_runs_tenant_idempotency', 'pipeline_runs', ['tenant_id', 'idempotency_key'], unique=True)
    op.create_table('ppenorm',
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ppenorm_position_id'), 'ppenorm', ['position_id'], unique=False)
    op.create_index(op.f('ix_ppenorm_tenant_id'), 'ppenorm', ['tenant_id'], unique=False)
    op.create_table('risk',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.Column('hazard', sa.String(length=512), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('controls', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_company_id'), 'risk', ['company_id'], unique=False)
    op.create_index(op.f('ix_risk_site_id'), 'risk', ['site_id'], unique=False)
    op.create_index(op.f('ix_risk_tenant_id'), 'risk', ['tenant_id'], unique=False)
    op.create_index('ix_risk_tenant_site', 'risk', ['tenant_id', 'site_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('place_id', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(length=128), nullable=True),
    sa.Column('hazard_id', sa.String(length=36), nullable=False),
    sa.Column('severity_before', sa.Integer(), nullable=False),
    sa.Column('likelihood_before', sa.Integer(), nullable=False),
    sa.Column('score_before', sa.Integer(), nullable=False),
    sa.Column('band_before', sa.String(length=16), nullable=False),
    sa.Column('controls', sa.Text(), nullable=True),
    sa.Column('severity_after', sa.Integer(), nullable=False),
    sa.Column('likelihood_after', sa.Integer(), nullable=False),
    sa.Column('score_after', sa.Integer(), nullable=False),
    sa.Column('band_after', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['hazard_id'], ['risk_hazards.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['site.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_assessment_tenant_job', 'risk_assessments', ['tenant_id', 'job_title'], unique=False)
    op.create_index(op.f('ix_risk_assessments_company_id'), 'risk_assessments', ['company_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_place_id'), 'risk_assessments', ['place_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_tenant_id'), 'risk_assessments', ['tenant_id'], unique=False)
    op.create_table('document',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=True),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'SIGNED', 'ARCHIVED', name='documentstatus'), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_created_at', 'document', ['created_at'], unique=False)
    op.create_index('ix_document_status', 'document', ['status'], unique=False)
    op.create_index('ix_document_tenant_created_at', 'document', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_document_tenant_id'), 'document', ['tenant_id'], unique=False)
    op.create_table('medical_exam',
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('exam_type', sa.String(length=128), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('conclusion', sa.String(length=255), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_exam_person_id'), 'medical_exam', ['person_id'], unique=False)
    op.create_index(op.f('ix_medical_exam_tenant_id'), 'medical_exam', ['tenant_id'], unique=False)
    op.create_table('permit',
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('permit_type', sa.String(length=128), nullable=False),
    sa.Column('issued_at', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'REVOKED', name='permitstatus'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permit_person_id'), 'permit', ['person_id'], unique=False)
    op.create_index(op.f('ix_permit_tenant_id'), 'permit', ['tenant_id'], unique=False)
    op.create_table('ppeissue',
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ISSUED', 'RETURNED', 'LOST', name='ppeissuestatus'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ppeissue_person_id'), 'ppeissue', ['person_id'], unique=False)
    op.create_index(op.f('ix_ppeissue_tenant_id'), 'ppeissue', ['tenant_id'], unique=False)
    op.create_table('training',
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'COMPLETED', name='trainingstatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_person_id'), 'training', ['person_id'], unique=False)
    op.create_index(op.f('ix_training_tenant_id'), 'training', ['tenant_id'], unique=False)
    op.create_table('violation',
    sa.Column('inspection_id', sa.String(length=36), nullable=False),
    sa.Column('clause_ref', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='violationseverity'), nullable=False),
    sa.Column('photo_key', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_violation_inspection_id', 'violation', ['inspection_id'], unique=False)
    op.create_index('ix_violation_severity', 'violation', ['severity'], unique=False)
    op.create_index(op.f('ix_violation_tenant_id'), 'violation', ['tenant_id'], unique=False)
    op.create_table('correctiveaction',
    sa.Column('violation_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE', name='correctiveactionstatus'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['violation_id'], ['violation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_corrective_action_due_date', 'correctiveaction', ['due_date'], unique=False)
    op.create_index('ix_corrective_action_status', 'correctiveaction', ['status'], unique=False)
    op.create_index('ix_corrective_action_violation_id', 'correctiveaction', ['violation_id'], unique=False)
    op.create_index(op.f('ix_correctiveaction_tenant_id'), 'correctiveaction', ['tenant_id'], unique=False)
    op.create_table('documentgenerationjob',
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('template_code', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'SUCCEEDED', 'FAILED', name='documentjobstatus'), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('initiated_by', sa.String(length=36), nullable=False),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['initiated_by'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_document_job_tenant_idempotency')
    )
    op.create_index('ix_document_job_task_id', 'documentgenerationjob', ['task_id'], unique=False)
    op.create_index(op.f('ix_documentgenerationjob_tenant_id'), 'documentgenerationjob', ['tenant_id'], unique=False)
    op.create_table('documentversion',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('template_version', sa.Text(), nullable=False),
    sa.Column('data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('file_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_version_created_at', 'documentversion', ['created_at'], unique=False)
    op.create_index('ix_document_version_document_id', 'documentversion', ['document_id'], unique=False)
    op.create_index(op.f('ix_documentversion_tenant_id'), 'documentversion', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documentversion_tenant_id'), table_name='documentversion')
    op.drop_index('ix_document_version_document_id', table_name='documentversion')
    op.drop_index('ix_document_version_created_at', table_name='documentversion')
    op.drop_table('documentversion')
    op.drop_index(op.f('ix_documentgenerationjob_tenant_id'), table_name='documentgenerationjob')
    op.drop_index('ix_document_job_task_id', table_name='documentgenerationjob')
    op.drop_table('documentgenerationjob')
    op.drop_index(op.f('ix_correctiveaction_tenant_id'), table_name='correctiveaction')
    op.drop_index('ix_corrective_action_violation_id', table_name='correctiveaction')
    op.drop_index('ix_corrective_action_status', table_name='correctiveaction')
    op.drop_index('ix_corrective_action_due_date', table_name='correctiveaction')
    op.drop_table('correctiveaction')
    op.drop_index(op.f('ix_violation_tenant_id'), table_name='violation')
    op.drop_index('ix_violation_severity', table_name='violation')
    op.drop_index('ix_violation_inspection_id', table_name='violation')
    op.drop_table('violation')
    op.drop_index(op.f('ix_training_tenant_id'), table_name='training')
    op.drop_index(op.f('ix_training_person_id'), table_name='training')
    op.drop_table('training')
    op.drop_index(op.f('ix_ppeissue_tenant_id'), table_name='ppeissue')
    op.drop_index(op.f('ix_ppeissue_person_id'), table_name='ppeissue')
    op.drop_table('ppeissue')
    op.drop_index(op.f('ix_permit_tenant_id'), table_name='permit')
    op.drop_index(op.f('ix_permit_person_id'), table_name='permit')
    op.drop_table('permit')
    op.drop_index(op.f('ix_medical_exam_tenant_id'), table_name='medical_exam')
    op.drop_index(op.f('ix_medical_exam_person_id'), table_name='medical_exam')
    op.drop_table('medical_exam')
    op.drop_index(op.f('ix_document_tenant_id'), table_name='document')
    op.drop_index('ix_document_tenant_created_at', table_name='document')
    op.drop_index('ix_document_status', table_name='document')
    op.drop_index('ix_document_created_at', table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_risk_assessments_tenant_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_place_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_company_id'), table_name='risk_assessments')
    op.drop_index('ix_risk_assessment_tenant_job', table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index('ix_risk_tenant_site', table_name='risk')
    op.drop_index(op.f('ix_risk_tenant_id'), table_name='risk')
    op.drop_index(op.f('ix_risk_site_id'), table_name='risk')
    op.drop_index(op.f('ix_risk_company_id'), table_name='risk')
    op.drop_table('risk')
    op.drop_index(op.f('ix_ppenorm_tenant_id'), table_name='ppenorm')
    op.drop_index(op.f('ix_ppenorm_position_id'), table_name='ppenorm')
    op.drop_table('ppenorm')
    op.drop_index('ix_pipeline_runs_tenant_idempotency', table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_tenant_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_template_version_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_template_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_idempotency_key'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_person_tenant_id'), table_name='person')
    op.drop_index(op.f('ix_person_company_id'), table_name='person')
    op.drop_table('person')
    op.drop_index(op.f('ix_npabinding_tenant_id'), table_name='npabinding')
    op.drop_index(op.f('ix_npabinding_template_version_id'), table_name='npabinding')
    op.drop_index(op.f('ix_npabinding_npa_id'), table_name='npabinding')
    op.drop_table('npabinding')
    op.drop_index(op.f('ix_inspection_tenant_id'), table_name='inspection')
    op.drop_index('ix_inspection_status', table_name='inspection')
    op.drop_index('ix_inspection_started_at', table_name='inspection')
    op.drop_index('ix_inspection_site_id', table_name='inspection')
    op.drop_index('ix_inspection_checklist_id', table_name='inspection')
    op.drop_table('inspection')
    op.drop_index(op.f('ix_templateversion_tenant_id'), table_name='templateversion')
    op.drop_index(op.f('ix_templateversion_template_id'), table_name='templateversion')
    op.drop_table('templateversion')
    op.drop_index(op.f('ix_site_tenant_id'), table_name='site')
    op.drop_index(op.f('ix_site_company_id'), table_name='site')
    op.drop_table('site')
    op.drop_index(op.f('ix_riskmap_tenant_id'), table_name='riskmap')
    op.drop_index(op.f('ix_riskmap_methodology_id'), table_name='riskmap')
    op.drop_table('riskmap')
    op.drop_index(op.f('ix_position_tenant_id'), table_name='position')
    op.drop_index(op.f('ix_position_company_id'), table_name='position')
    op.drop_table('position')
    op.drop_index(op.f('ix_packagepreset_tenant_id'), table_name='packagepreset')
    op.drop_index(op.f('ix_packagepreset_profile_id'), table_name='packagepreset')
    op.drop_table('packagepreset')
    op.drop_index(op.f('ix_equipment_tenant_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_asset_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_document_pack_item_tenant_id'), table_name='document_pack_item')
    op.drop_index(op.f('ix_document_pack_item_template_id'), table_name='document_pack_item')
    op.drop_index(op.f('ix_document_pack_item_pack_id'), table_name='document_pack_item')
    op.drop_table('document_pack_item')
    op.drop_index(op.f('ix_auditlog_tenant_id'), table_name='auditlog')
    op.drop_index('ix_auditlog_when', table_name='auditlog')
    op.drop_index('ix_auditlog_object', table_name='auditlog')
    op.drop_index('ix_auditlog_action', table_name='auditlog')
    op.drop_table('auditlog')
    op.drop_index(op.f('ix_warehouseppe_tenant_id'), table_name='warehouseppe')
    op.drop_table('warehouseppe')
    op.drop_index(op.f('ix_user_tenant_id'), table_name='user')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_template_tenant_id'), table_name='template')
    op.drop_index(op.f('ix_template_storage_key'), table_name='template')
    op.drop_index(op.f('ix_template_name'), table_name='template')
    op.drop_table('template')
    op.drop_index(op.f('ix_riskmethodology_tenant_id'), table_name='riskmethodology')
    op.drop_table('riskmethodology')
    op.drop_index(op.f('ix_risk_matrix_tenant_id'), table_name='risk_matrix')
    op.drop_table('risk_matrix')
    op.drop_index(op.f('ix_risk_hazards_tenant_id'), table_name='risk_hazards')
    op.drop_index('ix_risk_hazard_tenant_code', table_name='risk_hazards')
    op.drop_table('risk_hazards')
    op.drop_index(op.f('ix_risk_controls_tenant_id'), table_name='risk_controls')
    op.drop_index('ix_risk_control_tenant_code', table_name='risk_controls')
    op.drop_table('risk_controls')
    op.drop_index(op.f('ix_plantask_tenant_id'), table_name='plantask')
    op.drop_table('plantask')
    op.drop_index(op.f('ix_packageprofile_tenant_id'), table_name='packageprofile')
    op.drop_table('packageprofile')
    op.drop_index(op.f('ix_outbox_tenant_id'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_npa_clause_act_id'), table_name='npa_clause')
    op.drop_table('npa_clause')
    op.drop_index(op.f('ix_npa_tenant_id'), table_name='npa')
    op.drop_table('npa')
    op.drop_index(op.f('ix_journalentry_tenant_id'), table_name='journalentry')
    op.drop_table('journalentry')
    op.drop_index(op.f('ix_incident_tenant_id'), table_name='incident')
    op.drop_table('incident')
    op.drop_index(op.f('ix_idempotency_keys_tenant_id'), table_name='idempotency_keys')
    op.drop_index('ix_idempotency_keys_lookup', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_file_tenant_id'), table_name='file')
    op.drop_index('ix_file_storage_key', table_name='file')
    op.drop_index('ix_file_sha256', table_name='file')
    op.drop_table('file')
    op.drop_index(op.f('ix_featureenablement_tenant_id'), table_name='featureenablement')
    op.drop_index('ix_feature_enablement_on', table_name='featureenablement')
    op.drop_index('ix_feature_enablement_feature_id', table_name='featureenablement')
    op.drop_table('featureenablement')
    op.drop_index(op.f('ix_document_pack_tenant_id'), table_name='document_pack')
    op.drop_table('document_pack')
    op.drop_index(op.f('ix_company_tenant_id'), table_name='company')
    op.drop_table('company')
    op.drop_index('ix_checklist_title', table_name='checklist')
    op.drop_index(op.f('ix_checklist_tenant_id'), table_name='checklist')
    op.drop_index('ix_checklist_npa_code', table_name='checklist')
    op.drop_index('ix_checklist_created_at', table_name='checklist')
    op.drop_table('checklist')
    op.drop_index(op.f('ix_asset_tenant_id'), table_name='asset')
    op.drop_table('asset')
    op.drop_index(op.f('ix_api_key_tenant_id'), table_name='api_key')
    op.drop_table('api_key')
    op.drop_table('tenant')
    op.drop_table('npa_act')
    op.drop_table('feature')
    # ### end Alembic commands ###
