"""Convenient re-exports for ORM models used across the service."""

from app.models.api_deprecation_usage import ApiDeprecationUsage
from app.models.calendar_views import SavedCalendarView
from app.models.client_changes import ClientChange
from app.models.committees import (
    Committee,
    CommitteeAgendaItem,
    CommitteeDecision,
    CommitteeDecisionTask,
    CommitteeKind,
    CommitteeMeeting,
    CommitteeMember,
    CommitteeMemberRole,
    DecisionTaskStatus,
    MeetingStatus,
)
from app.models.compliance_requirements import (
    ComplianceRequirement,
    ComplianceRequirementEvidence,
)
from app.models.discipline_reports import DisciplineStatusReport
from app.models.document import (
    Document,
    DocumentBatchItem,
    DocumentBatchItemStatus,
    DocumentBatchRun,
    DocumentBatchStatus,
    DocumentSnapshot,
    DocumentStatus,
    DocumentVersion,
)
from app.models.file import File
from app.models.finance import (
    Contract,
    ContractStatus,
    Department,
    Invoice,
    InvoiceStatus,
    Order,
    OrderStatus,
)
from app.models.job_engine import InboundWebhookDedup
from app.models.legal_acceptance import TenantLegalAcceptance
from app.models.legal_documents import TenantLegalDocument
from app.models.managed_clients import (
    ManagedClient,
    ManagedClientAccess,
    ManagedClientContextSession,
)
from app.models.models import (
    ApiKey,
    ApprovalDecision,
    ApprovalDecisionType,
    ApprovalRequest,
    ApprovalRequestStatus,
    ApprovalRoute,
    Attestation,
    AttestationStatus,
    AuditLog,
    Branch,
    Company,
    DocumentPack,
    DocumentPackItem,
    EdoDirection,
    EdoMessage,
    EdoStatus,
    EdoStatusHistory,
    Incident,
    IncidentLog,
    IncidentPerson,
    IncidentPersonRole,
    IncidentStage,
    IncidentStatus,
    IncidentType,
    Inspection,
    InspectionResult,
    InspectionStatus,
    InspectionType,
    JournalEntry,
    MedicalExam,
    NPABinding,
    Outbox,
    OutboxStatus,
    PackagePreset,
    PackageProfile,
    Permit,
    Person,
    PipelineRun,
    PlanTask,
    PPEIssue,
    PPENorm,
    Prescription,
    PrescriptionStatus,
    RiskMap,
    RiskMethodology,
    SecurityAuditLog,
    SignatureType,
    Site,
    Template,
    TemplateVersion,
    Tenant,
    TenantSettings,
    Training,
    TrainingCertificate,
    TrainingCourse,
    TrainingPlan,
    TrainingSession,
    TrainingSessionStatus,
    TrainingStatus,
    User,
    UserRole,
    WebhookEndpoint,
    WebhookSubscription,
)
from app.models.notifications import (
    Notification,
    NotificationChannel,
    NotificationChannelSettings,
    NotificationStatus,
    NotificationType,
    ReminderEntityType,
)
from app.models.notifications import (
    PlanTask as CalendarPlanTask,
)
from app.models.notifications import (
    PlanTaskStatus as CalendarPlanTaskStatus,
)
from app.models.npa import NpaAct, NpaClause, NpaRevision, NpaRevisionClause
from app.models.npa_watch import NpaActResponsible
from app.models.obligations import Task, TaskPriority, TaskReminderChannel, TaskStatus
from app.models.risk import (
    RiskActionPlan,
    RiskActionPlanItem,
    RiskAssessment,
    RiskAssessmentItem,
    RiskCard,
    RiskControl,
    RiskHazard,
    RiskMatrixCell,
)
from app.models.safety_core import (
    Hazard as SafetyHazard,
)
from app.models.safety_core import (
    RiskMapItem,
    RiskMapItemMeasure,
    RiskMeasure,
    SafetyRiskMap,
    SafetyRiskMethodology,
)
from app.models.sout import (
    SoutCampaign,
    SoutCampaignStatus,
    SoutClass,
    SoutClassHistory,
    SoutFactor,
    SoutGuarantee,
    SoutGuaranteeKind,
    SoutWorkplace,
)
from app.models.sso import TenantSsoConfig
from app.models.white_label import TenantBranding
from app.models.work_permit import WorkPermit, WorkPermitEvent, WorkPermitMember

__all__ = [
    "TenantSsoConfig",
    "NpaActResponsible",
    "NpaRevisionClause",
    "TenantBranding",
    "ClientChange",
    "ComplianceRequirement",
    "ComplianceRequirementEvidence",
    "DisciplineStatusReport",
    "TenantLegalAcceptance",
    "TenantLegalDocument",
    "ApiDeprecationUsage",
    "Document",
    "DocumentBatchItem",
    "DocumentBatchItemStatus",
    "DocumentBatchRun",
    "DocumentBatchStatus",
    "InboundWebhookDedup",
    "DocumentSnapshot",
    "DocumentStatus",
    "DocumentVersion",
    "File",
    "AuditLog",
    "Attestation",
    "AttestationStatus",
    "ApiKey",
    "Branch",
    "Company",
    "Contract",
    "ContractStatus",
    "Department",
    "DocumentPack",
    "DocumentPackItem",
    "Incident",
    "IncidentLog",
    "IncidentPerson",
    "IncidentPersonRole",
    "IncidentStatus",
    "IncidentType",
    "IncidentStage",
    "JournalEntry",
    "ManagedClient",
    "ManagedClientAccess",
    "ManagedClientContextSession",
    "MedicalExam",
    "NPABinding",
    "NpaAct",
    "NpaClause",
    "NpaRevision",
    "Outbox",
    "OutboxStatus",
    "PackagePreset",
    "PackageProfile",
    "Person",
    "PipelineRun",
    "PlanTask",
    "Invoice",
    "InvoiceStatus",
    "Inspection",
    "InspectionResult",
    "InspectionStatus",
    "InspectionType",
    "PPEIssue",
    "PPENorm",
    "Permit",
    "Order",
    "OrderStatus",
    "RiskActionPlan",
    "RiskActionPlanItem",
    "RiskAssessment",
    "RiskAssessmentItem",
    "RiskCard",
    "RiskControl",
    "RiskHazard",
    "RiskMatrixCell",
    "SafetyHazard",
    "SafetyRiskMap",
    "RiskMapItem",
    "RiskMapItemMeasure",
    "RiskMeasure",
    "SafetyRiskMethodology",
    "RiskMap",
    "SecurityAuditLog",
    "RiskMethodology",
    "Site",
    "Prescription",
    "PrescriptionStatus",
    "Task",
    "TaskPriority",
    "TaskReminderChannel",
    "TaskStatus",
    "Template",
    "TemplateVersion",
    "Tenant",
    "TenantSettings",
    "Training",
    "TrainingCertificate",
    "TrainingCourse",
    "TrainingPlan",
    "TrainingSession",
    "TrainingSessionStatus",
    "TrainingStatus",
    "User",
    "UserRole",
    "WebhookSubscription",
    "WebhookEndpoint",
    "ApprovalRoute",
    "ApprovalRequest",
    "ApprovalDecision",
    "ApprovalRequestStatus",
    "ApprovalDecisionType",
    "SignatureType",
    "EdoMessage",
    "EdoStatusHistory",
    "EdoDirection",
    "EdoStatus",
    "Notification",
    "NotificationChannel",
    "NotificationChannelSettings",
    "NotificationStatus",
    "NotificationType",
    "ReminderEntityType",
    "CalendarPlanTask",
    "CalendarPlanTaskStatus",
    "SavedCalendarView",
    "WorkPermit",
    "WorkPermitMember",
    "WorkPermitEvent",
    "Committee",
    "CommitteeAgendaItem",
    "CommitteeDecision",
    "CommitteeDecisionTask",
    "CommitteeKind",
    "CommitteeMeeting",
    "CommitteeMember",
    "CommitteeMemberRole",
    "DecisionTaskStatus",
    "MeetingStatus",
    "SoutCampaign",
    "SoutCampaignStatus",
    "SoutClass",
    "SoutClassHistory",
    "SoutFactor",
    "SoutGuarantee",
    "SoutGuaranteeKind",
    "SoutWorkplace",
]
