from __future__ import annotations

from typing import TYPE_CHECKING

# ARCH-2: re-export approval_runtime models moved to app.models.approval_runtime.
from app.models.approval_runtime import (
    ApprovalDecisionLog,
    ApprovalInstance,
    ApprovalInstanceStep,
    ApprovalProcess,
    ApprovalProcessStatus,
    ApprovalRouteStep,
    ApprovalTask,
    ApprovalTaskStatus,
    EdoStatusEvent,
    EdoWebhookInbox,
    Outbox,
    OutboxStatus,
    SignatureRequest,
    SignatureRequestStatus,
    WebhookDelivery,
    WebhookEndpoint,
)
from app.models.approval_workflow import (
    ApprovalDecision,
    ApprovalDecisionType,
    ApprovalInstanceStatus,
    ApprovalInstanceStepStatus,
    ApprovalRequest,
    ApprovalRequestStatus,
    ApprovalRoute,
    ApprovalRouteAppliesTo,
    ApprovalRouteStatus,
    ApprovalStepType,
    EdoDirection,
    EdoMessage,
    EdoMessageStatus,
    EdoReceipt,
    EdoStatus,
    EdoStatusHistory,
    SignatureProviderStatus,
    SignatureType,
)

# ARCH-2: re-export assets models moved to app.models.assets.
from app.models.assets import (
    Asset,
    Equipment,
    EquipmentStatus,
)

# ARCH-2: re-export audit_log-domain models moved to app.models.audit_log.
from app.models.audit_log import (
    AuditExportJob,
    AuditLog,
    SecurityAuditLog,
)

# Re-export declarative bases (kept in __all__ so ruff keeps them) — historically
# importable from app.models.models; canonical home is app.models.base.
from app.models.base import SharedModel, TenantBaseModel

# ARCH-2: re-export briefings-domain models moved to app.models.briefings.
from app.models.briefings import (
    BriefingEntry,
    BriefingJournal,
    BriefingSignature,
    BriefingTemplate,
)

# ARCH-2: re-export field_ops-domain models moved to app.models.field_ops.
from app.models.field_ops import (
    CalendarEvent,
    ComplianceDeadline,
    ExternalRegistryJob,
    OfflineMediaQueue,
    OfflineSyncBatch,
    Permit,
    PermitStatus,
)

# Re-export File (kept in __all__ so ruff F401 keeps it; some callers do
# ``from app.models.models import File``).
from app.models.file import File

# ARCH-2: re-export idempotency models moved to app.models.idempotency.
from app.models.idempotency import (
    IdempotencyKey,
    IdempotencyStatus,
)

# ARCH-2: re-export identity models moved to app.models.identity.
from app.models.identity import (
    ApiKey,
    AuthzBaseModel,
    AuthzPermission,
    AuthzPolicy,
    AuthzRole,
    AuthzRolePermission,
    AuthzUserRole,
    RefreshSession,
    User,
    UserAttribute,
    UserRole,
)

# ARCH-2: re-export incidents-domain models moved to app.models.incidents.
from app.models.incidents import (
    Incident,
    IncidentLog,
    IncidentPerson,
    IncidentPersonRole,
    IncidentSeverity,
    IncidentStage,
    IncidentStatus,
    IncidentType,
)

# ARCH-2: re-export inspections-domain models moved to app.models.inspections.
from app.models.inspections import (
    Attestation,
    AttestationStatus,
    Inspection,
    InspectionResult,
    InspectionStatus,
    InspectionType,
    Prescription,
    PrescriptionStatus,
)

# ARCH-2: re-export journals-domain models moved to app.models.journals.
from app.models.journals import (
    Journal,
    JournalEntry,
    JournalType,
    PlanTask,
    PlanTaskStatus,
)

# ARCH-2: re-export marketplace models moved to app.models.marketplace.
from app.models.marketplace import (
    MarketplaceCatalogItem,
)

# ARCH-2: re-export master_data models moved to app.models.master_data.
from app.models.master_data import (
    Branch,
    Company,
    EmploymentStatus,
    Person,
    Position,
    Site,
    Workplace,
)

# ARCH-2: re-export medical-domain models moved to app.models.medical.
from app.models.medical import (
    MedicalExam,
    MedicalExamKind,
    MedicalFactor,
    MedicalFitness,
    MedicalNorm,
    MedicalReferral,
    MedicalReferralStatus,
    MedicalSuspension,
    MedicalSuspensionReason,
    MedicalSuspensionStatus,
    PsychiatricActivityType,
    PsychiatricPositionActivity,
)

# ARCH-2: re-export packages-domain models moved to app.models.packages.
from app.models.packages import (
    ClientPackagePreset,
    ClientPackageRun,
    ClientPortalToken,
    ClientRequestTicket,
    ClientRequestTicketStatus,
    DocumentPack,
    DocumentPackItem,
    DocumentPackModule,
    DocumentPackScenario,
    OutputFormat,
    PackageEntityStatus,
    PackageEvent,
    PackagePreset,
    PackagePresetConfig,
    PackagePresetItem,
    PackageProfile,
    PackageProfileConfig,
    PackageRequirement,
    PackageRequirementStatus,
    PackageRequirementType,
    PackageRunStatus,
    PackageSourceType,
    PackLogLevel,
    PackRun,
    PackRunItem,
    PackRunItemStatus,
    PackRunLifecycleStatus,
    PackRunLog,
    PipelineRun,
    PipelineRunStatus,
    ReplaceMode,
)

# ARCH-2: re-export ppe-domain models moved to app.models.ppe.
from app.models.ppe import (
    PPEInventoryCount,
    PPEInventoryCountLine,
    PPEIssue,
    PPEIssueStatus,
    PPEItem,
    PPEItemCategory,
    PPENorm,
    PPESafetyBudget,
    PPEStockBatch,
    PPEStockMovement,
    PPESupplier,
)

# P10-07 rb01: re-export report-builder models from app.models.report_builder.
from app.models.report_builder import ReportDefinition

# ARCH-2: re-export risk_register models moved to app.models.risk_register.
from app.models.risk_register import (
    NPA,
    NPABinding,
    NpaBindingTarget,
    NPAStatus,
    PositionHazardLink,
    RiskMap,
    RiskMethodology,
    WorkplaceHazardLink,
)

# ARCH-2: re-export templates-domain models moved to app.models.templates.
from app.models.templates import (
    Template,
    TemplateStatus,
    TemplateUsage,
    TemplateVersion,
    TemplateVersionStatus,
)

# ARCH-2: re-export tenant_billing models moved to app.models.tenant_billing.
from app.models.tenant_billing import (
    ApiToken,
    BillingEvent,
    BillingEventType,
    BillingInvoice,
    BillingInvoiceStatus,
    BillingPlan,
    BillingSubscription,
    BillingSubscriptionStatus,
    BillingUsageCounter,
    RoleEnum,
    Tenant,
    TenantCounter,
    TenantIntegrationKey,
    TenantLimitOverride,
    TenantQuota,
    TenantQuotaCounter,
    TenantRateLimit,
    TenantSettings,
    WebhookSubscription,
)

# ARCH-2: Training-domain models moved to app.models.training; re-exported
# here so ``from app.models.models import Training...`` keeps working. All names
# are listed in __all__ below so ruff (F401) does not strip these re-exports.
from app.models.training import (
    Training,
    TrainingAttempt,
    TrainingCertificate,
    TrainingCourse,
    TrainingEnrollment,
    TrainingGroup,
    TrainingLesson,
    TrainingModule,
    TrainingPlan,
    TrainingProgram,
    TrainingProtocol,
    TrainingProtocolItem,
    TrainingSession,
    TrainingSessionStatus,
    TrainingStatus,
    TrainingTest,
    TrainingTestQuestion,
)

if TYPE_CHECKING:  # pragma: no cover - used for type checkers only
    pass

__all__ = [
    "AuditLog",
    "AuditExportJob",
    "ApiKey",
    "Branch",
    "Company",
    "PipelineRun",
    "PipelineRunStatus",
    "IdempotencyKey",
    "IdempotencyStatus",
    "Equipment",
    "Incident",
    "IncidentLog",
    "IncidentPerson",
    "IncidentPersonRole",
    "IncidentStatus",
    "IncidentType",
    "IncidentStage",
    "JournalEntry",
    "NPA",
    "NPABinding",
    "NpaBindingTarget",
    "Inspection",
    "InspectionStatus",
    "InspectionType",
    "InspectionResult",
    "Attestation",
    "AttestationStatus",
    "Prescription",
    "PrescriptionStatus",
    "Outbox",
    "OutboxStatus",
    "PackagePreset",
    "PackageProfile",
    "Site",
    "MedicalExam",
    "MedicalExamKind",
    "MedicalFitness",
    "MedicalReferralStatus",
    "MedicalSuspensionStatus",
    "MedicalSuspensionReason",
    "MedicalNorm",
    "MedicalReferral",
    "MedicalSuspension",
    "PsychiatricActivityType",
    "PsychiatricPositionActivity",
    "DocumentPack",
    "DocumentPackItem",
    "DocumentPackModule",
    "DocumentPackScenario",
    "Permit",
    "Person",
    "EmploymentStatus",
    "PlanTask",
    "Position",
    "PPENorm",
    "PPEItemCategory",
    "PPEItem",
    "PPEIssue",
    "JournalType",
    "RiskMap",
    "RiskMethodology",
    "Workplace",
    "WorkplaceHazardLink",
    "PositionHazardLink",
    "Journal",
    "JournalEntry",
    "Tenant",
    "TenantQuota",
    "TenantCounter",
    "TenantSettings",
    "TenantIntegrationKey",
    "TenantQuotaCounter",
    "BillingPlan",
    "BillingSubscription",
    "BillingSubscriptionStatus",
    "BillingUsageCounter",
    "BillingInvoice",
    "BillingInvoiceStatus",
    "BillingEvent",
    "BillingEventType",
    "ApiToken",
    "TenantRateLimit",
    "TenantLimitOverride",
    "Template",
    "TemplateStatus",
    "TemplateVersion",
    "TemplateUsage",
    "Training",
    "TrainingStatus",
    "TrainingCourse",
    "TrainingPlan",
    "TrainingSession",
    "TrainingSessionStatus",
    "TrainingCertificate",
    "TrainingProgram",
    "TrainingModule",
    "TrainingLesson",
    "TrainingTest",
    "TrainingTestQuestion",
    "TrainingGroup",
    "TrainingEnrollment",
    "TrainingAttempt",
    "TrainingProtocol",
    "TrainingProtocolItem",
    "User",
    "RefreshSession",
    "UserRole",
    "UserAttribute",
    "AuthzRole",
    "AuthzPermission",
    "AuthzRolePermission",
    "AuthzUserRole",
    "WebhookSubscription",
    "WebhookEndpoint",
    "WebhookDelivery",
    "ApprovalRoute",
    "ApprovalRouteAppliesTo",
    "ApprovalRouteStatus",
    "ApprovalRouteStep",
    "ApprovalInstance",
    "ApprovalInstanceStep",
    "ApprovalInstanceStatus",
    "ApprovalInstanceStepStatus",
    "ApprovalStepType",
    "SignatureProviderStatus",
    "ApprovalRequest",
    "ApprovalDecision",
    "ApprovalRequestStatus",
    "ApprovalDecisionType",
    "SignatureType",
    "EdoMessage",
    "EdoReceipt",
    "EdoStatusHistory",
    "EdoDirection",
    "EdoStatus",
    "EdoMessageStatus",
]

# ARCH-2 batch 5 re-exports (kept in __all__ so ruff F401 keeps the imports).
__all__ += [
    "RoleEnum",
    "Tenant",
    "TenantQuota",
    "TenantSettings",
    "TenantCounter",
    "TenantIntegrationKey",
    "TenantQuotaCounter",
    "BillingSubscriptionStatus",
    "BillingPlan",
    "BillingSubscription",
    "BillingUsageCounter",
    "BillingInvoiceStatus",
    "BillingInvoice",
    "BillingEventType",
    "BillingEvent",
    "TenantRateLimit",
    "ApiToken",
    "TenantLimitOverride",
    "WebhookSubscription",
    "User",
    "RefreshSession",
    "UserRole",
    "UserAttribute",
    "AuthzBaseModel",
    "AuthzRole",
    "AuthzPermission",
    "AuthzRolePermission",
    "AuthzUserRole",
    "AuthzPolicy",
    "ApiKey",
]

# ARCH-2 batch 4 re-exports (kept in __all__ so ruff F401 keeps the imports).
__all__ += [
    "OutboxStatus",
    "ApprovalProcessStatus",
    "ApprovalTaskStatus",
    "ApprovalProcess",
    "ApprovalTask",
    "ApprovalDecisionLog",
    "ApprovalRouteStep",
    "ApprovalInstance",
    "ApprovalInstanceStep",
    "EdoStatusEvent",
    "EdoWebhookInbox",
    "SignatureRequestStatus",
    "SignatureRequest",
    "Outbox",
    "WebhookDelivery",
    "WebhookEndpoint",
]

# ARCH-2 batch 3 re-exports (kept in __all__ so ruff F401 keeps the imports).
__all__ += [
    "File",
    "SharedModel",
    "TenantBaseModel",
    "Company",
    "Position",
    "EmploymentStatus",
    "Person",
    "Site",
    "Workplace",
    "MarketplaceCatalogItem",
    "IdempotencyStatus",
    "IdempotencyKey",
    "RiskMethodology",
    "RiskMap",
    "WorkplaceHazardLink",
    "PositionHazardLink",
    "NPAStatus",
    "NPA",
    "NpaBindingTarget",
    "NPABinding",
    "Asset",
    "EquipmentStatus",
    "Equipment",
]

# ARCH-2 batch 2 re-exports (kept in __all__ so ruff F401 keeps the imports).
__all__ += [
    "PackageEntityStatus",
    "PackageSourceType",
    "ReplaceMode",
    "OutputFormat",
    "PackRunLifecycleStatus",
    "PackRunItemStatus",
    "PackLogLevel",
    "PackageProfileConfig",
    "PackagePresetConfig",
    "PackagePresetItem",
    "PackRun",
    "PackRunItem",
    "PackRunLog",
    "PackageProfile",
    "PackagePreset",
    "DocumentPackModule",
    "DocumentPackScenario",
    "DocumentPack",
    "DocumentPackItem",
    "PipelineRunStatus",
    "PipelineRun",
    "PackageRunStatus",
    "PackageRequirementType",
    "PackageRequirementStatus",
    "ClientRequestTicketStatus",
    "ClientPackagePreset",
    "ClientPackageRun",
    "PackageRequirement",
    "ClientPortalToken",
    "ClientRequestTicket",
    "PackageEvent",
    "AuditLog",
    "AuditExportJob",
    "SecurityAuditLog",
    "JournalType",
    "Journal",
    "JournalEntry",
    "PlanTaskStatus",
    "PlanTask",
    "IncidentSeverity",
    "IncidentType",
    "IncidentStatus",
    "IncidentStage",
    "Incident",
    "IncidentPersonRole",
    "IncidentPerson",
    "IncidentLog",
    "InspectionStatus",
    "InspectionType",
    "Inspection",
    "InspectionResult",
    "AttestationStatus",
    "Attestation",
    "PrescriptionStatus",
    "Prescription",
]

# ARCH-2 batch 1 re-exports (kept in __all__ so ruff F401 keeps the imports).
__all__ += [
    "MedicalExamKind",
    "MedicalFitness",
    "MedicalReferralStatus",
    "MedicalSuspensionStatus",
    "MedicalSuspensionReason",
    "MedicalExam",
    "MedicalNorm",
    "MedicalFactor",
    "MedicalReferral",
    "MedicalSuspension",
    "PsychiatricActivityType",
    "PsychiatricPositionActivity",
    "BriefingTemplate",
    "BriefingJournal",
    "BriefingEntry",
    "BriefingSignature",
    "ComplianceDeadline",
    "CalendarEvent",
    "OfflineSyncBatch",
    "OfflineMediaQueue",
    "ExternalRegistryJob",
    "PermitStatus",
    "Permit",
    "PPENorm",
    "PPEItemCategory",
    "PPEItem",
    "PPEIssueStatus",
    "PPEIssue",
    "PPEStockBatch",
    "PPEStockMovement",
    "PPESupplier",
    "PPESafetyBudget",
    "PPEInventoryCount",
    "PPEInventoryCountLine",
    "TemplateStatus",
    "Template",
    "TemplateVersionStatus",
    "TemplateVersion",
    "TemplateUsage",
]

__all__ += ["ReportDefinition"]
