#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def pct(numerator: float, denominator: float) -> float:
    if denominator <= 0:
        return 100.0
    return (numerator / denominator) * 100.0


def collect_module_stats(coverage: dict[str, Any], patterns: list[str]) -> tuple[float, float, int, int]:
    files = coverage.get("files", {})
    statements = covered_lines = branches = covered_branches = 0

    for file_path, file_data in files.items():
        if not any(file_path == pattern or file_path.startswith(pattern) for pattern in patterns):
            continue
        summary = file_data.get("summary", {})
        statements += int(summary.get("num_statements", 0))
        covered_lines += int(summary.get("covered_lines", 0))
        branches += int(summary.get("num_branches", 0))
        covered_branches += int(summary.get("covered_branches", 0))

    line_pct = pct(covered_lines, statements)
    branch_pct = pct(covered_branches, branches)
    return line_pct, branch_pct, statements, branches


def main() -> int:
    parser = argparse.ArgumentParser(description="Fail CI when backend coverage regresses below baseline.")
    parser.add_argument(
        "--coverage-json",
        default="artifacts/coverage.json",
        help="Coverage JSON generated by pytest-cov / coverage.py",
    )
    parser.add_argument(
        "--baseline",
        default="docs/stabilization/backend_coverage_baseline.json",
        help="Committed baseline threshold config",
    )
    args = parser.parse_args()

    coverage_path = Path(args.coverage_json)
    baseline_path = Path(args.baseline)

    coverage = load_json(coverage_path)
    baseline = load_json(baseline_path)

    errors: list[str] = []
    totals = coverage.get("totals", {})

    overall_line = float(totals.get("percent_covered", 0.0))
    overall_branch = pct(float(totals.get("covered_branches", 0.0)), float(totals.get("num_branches", 0.0)))

    min_overall = baseline.get("overall", {})
    min_line = float(min_overall.get("line_percent", 0.0))
    min_branch = float(min_overall.get("branch_percent", 0.0))

    if overall_line < min_line:
        errors.append(f"overall line coverage {overall_line:.2f}% is below baseline {min_line:.2f}%")
    if overall_branch < min_branch:
        errors.append(f"overall branch coverage {overall_branch:.2f}% is below baseline {min_branch:.2f}%")

    print(f"[coverage] overall line={overall_line:.2f}% (min {min_line:.2f}%), branch={overall_branch:.2f}% (min {min_branch:.2f}%)")

    for module_name, module_cfg in baseline.get("modules", {}).items():
        patterns = list(module_cfg.get("patterns", []))
        module_line_min = float(module_cfg.get("line_percent", 0.0))
        module_branch_min = float(module_cfg.get("branch_percent", 0.0))
        module_line, module_branch, statements, branches = collect_module_stats(coverage, patterns)

        print(
            f"[coverage] {module_name}: line={module_line:.2f}% (min {module_line_min:.2f}%), "
            f"branch={module_branch:.2f}% (min {module_branch_min:.2f}%), "
            f"statements={statements}, branches={branches}"
        )

        if module_line < module_line_min:
            errors.append(
                f"{module_name} line coverage {module_line:.2f}% is below baseline {module_line_min:.2f}%"
            )
        if module_branch < module_branch_min:
            errors.append(
                f"{module_name} branch coverage {module_branch:.2f}% is below baseline {module_branch_min:.2f}%"
            )

    if errors:
        print("\nCoverage regression detected:")
        for error in errors:
            print(f" - {error}")
        return 1

    print("\nCoverage baseline check passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
