export const PERMISSIONS = {
  DASHBOARD_VIEW: "dashboard.view",
  ANALYTICS_VIEW: "analytics.view",
  COMPANY_VIEW: "company.view",
  PERSON_VIEW: "person.view",
  TEMPLATE_VIEW: "template.view",
  TEMPLATE_CREATE: "template.create",
  TEMPLATE_EDIT: "template.edit",
  TEMPLATE_DELETE: "template.delete",
  TEMPLATE_ACTIVATE: "template.activate",
  PACK_VIEW: "pack.view",
  GENERATION_VIEW: "generation.view",
  DOCUMENT_VIEW: "doc.view",
  DOCUMENT_CREATE: "doc.create",
  DOCUMENT_SIGN: "doc.sign",
  DOCUMENT_EXPORT: "doc.export",
  FILE_VIEW: "file.view",
  TASK_VIEW: "task.view",
  TASK_UPDATE: "task.update",
  RISK_VIEW: "risk.view",
  RISK_ASSESS: "risk.assess",
  RISK_EDIT: "risk.edit",
  RISK_EXPORT: "risk.export",
  ACTIVITY_VIEW: "activity.view",
  PPE_VIEW: "ppe.view",
  PPE_ISSUE: "ppe.issue",
  WAREHOUSE_VIEW: "warehouse.view",
  TRAINING_VIEW: "training.view",
  TRAINING_ASSIGN: "training.assign",
  TRAINING_COMPLETE: "training.complete",
  MEDICAL_VIEW: "medical.view",
  PERMIT_VIEW: "permit.view",
  PERMIT_MANAGE: "permit.manage",
  INCIDENT_VIEW: "incident.view",
  INCIDENT_CREATE: "incident.create",
  INSPECTION_VIEW: "inspection.view",
  INSPECTION_CREATE: "inspection.create",
  AUDIT_PREP_VIEW: "audit_prep.view",
  FIRE_SAFETY_VIEW: "fire_safety.view",
  FIRE_TRAINING_VIEW: "fire_training.view",
  FIRE_INSPECTIONS_VIEW: "fire_inspections.view",
  REFERENCE_VIEW: "reference.view",
  CONTRACTOR_VIEW: "contractor.view",
  CONTRACTOR_MANAGE: "contractor.manage",
  CRM_FINANCE_VIEW: "crm_finance.view",
  INTEGRATIONS_VIEW: "integrations.view",
  CLIENT_PORTAL_VIEW: "client_portal.view",
  ADMIN_MANAGE_ROLES: "admin.manage_roles",
  ADMIN_MANAGE_TENANTS: "admin.manage_tenants",
  NPA_VIEW: "npa.view",
  AUDIT_VIEW: "audit.view",
  SETTINGS_VIEW: "settings.view",
  REPORTS_VIEW: "reports.view",
  COMPANY_CREATE: "company.create",
  PERSON_CREATE: "person.create",
  WORKFLOW_MANAGE: "workflow.manage",
  ADMIN_OUTBOX_MANAGE: "admin.outbox_manage",
  DATA_QUALITY_VIEW: "data_quality.view",
  EMPLOYEE_CARD_VIEW: "employee_card.view",
  CALENDAR_VIEW: "calendar.view",
  WORK_PERMIT_VIEW: "work_permit.view",
  WORK_PERMIT_MANAGE: "work_permit.manage",
  COMMITTEE_VIEW: "committee.view",
  MANAGED_CLIENTS_VIEW: "managed_clients.view",
  SOUT_VIEW: "sout.view",
  BRANCH_VIEW: "branch.view",
  BRANCH_MANAGE: "branch.manage",
  RULES_VIEW: "rules.view",
  RULES_MANAGE: "rules.manage",
  BUDGET_VIEW: "budget.view",
  BUDGET_MANAGE: "budget.manage",
  IMPORTS_MANAGE: "imports.manage",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS: Permission[] = Object.values(PERMISSIONS);

export type Role =
  | "owner"
  | "admin"
  | "methodist"
  | "lawyer"
  | "project_manager"
  | "executor"
  | "office_manager"
  | "trainer"
  | "student"
  | "ot_pb_head"
  | "ot_specialist"
  | "pb_engineer"
  | "ecologist"
  | "hr"
  | "accountant"
  | "line_manager"
  | "client"
  | "auditor_ro"
  | "contractor_inspector"
  | "worker";

const baseOpsPermissions: Permission[] = [
  PERMISSIONS.DASHBOARD_VIEW,
  PERMISSIONS.DOCUMENT_VIEW,
  PERMISSIONS.DOCUMENT_CREATE,
  PERMISSIONS.GENERATION_VIEW,
  PERMISSIONS.PACK_VIEW,
  PERMISSIONS.TASK_VIEW,
  PERMISSIONS.FILE_VIEW
];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  owner: ALL_PERMISSIONS,
  admin: ALL_PERMISSIONS,
  methodist: [...baseOpsPermissions, PERMISSIONS.TEMPLATE_VIEW, PERMISSIONS.TEMPLATE_CREATE, PERMISSIONS.TEMPLATE_EDIT],
  lawyer: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.DOCUMENT_VIEW, PERMISSIONS.DOCUMENT_SIGN, PERMISSIONS.DOCUMENT_EXPORT],
  // BIZ-49 (разд. 49.2): «Аутсорсер / руководитель проектов» — целевая роль
  // единого окна ведения клиентов.
  project_manager: [...baseOpsPermissions, PERMISSIONS.COMPANY_VIEW, PERMISSIONS.PERSON_VIEW, PERMISSIONS.REPORTS_VIEW, PERMISSIONS.CLIENT_PORTAL_VIEW, PERMISSIONS.MANAGED_CLIENTS_VIEW],
  executor: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.DOCUMENT_VIEW, PERMISSIONS.TASK_VIEW, PERMISSIONS.PPE_VIEW, PERMISSIONS.TRAINING_VIEW, PERMISSIONS.INCIDENT_VIEW],
  office_manager: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.DOCUMENT_VIEW, PERMISSIONS.DOCUMENT_CREATE, PERMISSIONS.FILE_VIEW, PERMISSIONS.TASK_VIEW],
  trainer: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.TRAINING_VIEW, PERMISSIONS.TRAINING_ASSIGN, PERMISSIONS.TRAINING_COMPLETE],
  student: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.TRAINING_VIEW],
  ot_pb_head: ALL_PERMISSIONS.filter((permission) => permission !== PERMISSIONS.ADMIN_MANAGE_TENANTS),
  ot_specialist: [
    ...baseOpsPermissions,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.PERSON_VIEW,
    PERMISSIONS.TEMPLATE_VIEW,
    PERMISSIONS.DOCUMENT_EXPORT,
    PERMISSIONS.RISK_VIEW,
    PERMISSIONS.RISK_ASSESS,
    PERMISSIONS.RISK_EXPORT,
    PERMISSIONS.PPE_VIEW,
    PERMISSIONS.PPE_ISSUE,
    PERMISSIONS.WAREHOUSE_VIEW,
    PERMISSIONS.TRAINING_VIEW,
    PERMISSIONS.TRAINING_ASSIGN,
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.INCIDENT_VIEW,
    PERMISSIONS.INCIDENT_CREATE,
    PERMISSIONS.INSPECTION_VIEW,
    PERMISSIONS.INSPECTION_CREATE,
    PERMISSIONS.AUDIT_PREP_VIEW,
    PERMISSIONS.NPA_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.COMPANY_CREATE,
    PERMISSIONS.PERSON_CREATE,
    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.ANALYTICS_VIEW
  ],
  pb_engineer: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_EXPORT,
    PERMISSIONS.FIRE_SAFETY_VIEW,
    PERMISSIONS.FIRE_TRAINING_VIEW,
    PERMISSIONS.FIRE_INSPECTIONS_VIEW,
    PERMISSIONS.INSPECTION_VIEW,
    PERMISSIONS.INSPECTION_CREATE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.INCIDENT_VIEW,
    PERMISSIONS.INCIDENT_CREATE,
    PERMISSIONS.AUDIT_PREP_VIEW,
    PERMISSIONS.CALENDAR_VIEW
  ],
  ecologist: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.DOCUMENT_VIEW, PERMISSIONS.DOCUMENT_EXPORT, PERMISSIONS.RISK_VIEW, PERMISSIONS.RISK_EXPORT, PERMISSIONS.AUDIT_VIEW, PERMISSIONS.CALENDAR_VIEW],
  hr: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.PERSON_VIEW, PERMISSIONS.PERSON_CREATE, PERMISSIONS.TRAINING_VIEW, PERMISSIONS.TRAINING_ASSIGN, PERMISSIONS.TRAINING_COMPLETE, PERMISSIONS.TASK_VIEW, PERMISSIONS.TASK_UPDATE, PERMISSIONS.DATA_QUALITY_VIEW, PERMISSIONS.EMPLOYEE_CARD_VIEW, PERMISSIONS.CALENDAR_VIEW, PERMISSIONS.ANALYTICS_VIEW],
  accountant: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.DOCUMENT_VIEW, PERMISSIONS.DOCUMENT_EXPORT, PERMISSIONS.CRM_FINANCE_VIEW, PERMISSIONS.REPORTS_VIEW, PERMISSIONS.BUDGET_VIEW, PERMISSIONS.BUDGET_MANAGE],
  line_manager: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.DOCUMENT_VIEW, PERMISSIONS.DOCUMENT_EXPORT, PERMISSIONS.TRAINING_VIEW, PERMISSIONS.PPE_VIEW, PERMISSIONS.REPORTS_VIEW, PERMISSIONS.TASK_VIEW, PERMISSIONS.TASK_UPDATE, PERMISSIONS.DATA_QUALITY_VIEW, PERMISSIONS.EMPLOYEE_CARD_VIEW, PERMISSIONS.CALENDAR_VIEW, PERMISSIONS.ANALYTICS_VIEW],
  client: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.CLIENT_PORTAL_VIEW, PERMISSIONS.DOCUMENT_VIEW, PERMISSIONS.REPORTS_VIEW],
  auditor_ro: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.DOCUMENT_VIEW, PERMISSIONS.REPORTS_VIEW, PERMISSIONS.AUDIT_VIEW],
  worker: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.DOCUMENT_VIEW, PERMISSIONS.TRAINING_VIEW],
  contractor_inspector: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.INSPECTION_VIEW,
    PERMISSIONS.FIRE_INSPECTIONS_VIEW,
    PERMISSIONS.CONTRACTOR_VIEW
  ]
};
