export const PERMISSIONS = {
  DASHBOARD_VIEW: "dashboard.view",
  COMPANY_VIEW: "company.view",
  PERSON_VIEW: "person.view",
  TEMPLATE_VIEW: "template.view",
  TEMPLATE_CREATE: "template.create",
  TEMPLATE_EDIT: "template.edit",
  TEMPLATE_DELETE: "template.delete",
  TEMPLATE_ACTIVATE: "template.activate",
  PACK_VIEW: "pack.view",
  DOCUMENT_VIEW: "doc.view",
  DOCUMENT_CREATE: "doc.create",
  DOCUMENT_SIGN: "doc.sign",
  DOCUMENT_EXPORT: "doc.export",
  FILE_VIEW: "file.view",
  TASK_VIEW: "task.view",
  RISK_VIEW: "risk.view",
  RISK_ASSESS: "risk.assess",
  RISK_EDIT: "risk.edit",
  RISK_EXPORT: "risk.export",
  ACTIVITY_VIEW: "activity.view",
  PPE_VIEW: "ppe.view",
  PPE_ISSUE: "ppe.issue",
  TRAINING_VIEW: "training.view",
  TRAINING_ASSIGN: "training.assign",
  TRAINING_COMPLETE: "training.complete",
  MEDICAL_VIEW: "medical.view",
  INCIDENT_VIEW: "incident.view",
  INSPECTION_VIEW: "inspection.view",
  AUDIT_PREP_VIEW: "audit_prep.view",
  FIRE_SAFETY_VIEW: "fire_safety.view",
  FIRE_TRAINING_VIEW: "fire_training.view",
  FIRE_INSPECTIONS_VIEW: "fire_inspections.view",
  REFERENCE_VIEW: "reference.view",
  CONTRACTOR_VIEW: "contractor.view",
  ADMIN_MANAGE_ROLES: "admin.manage_roles",
  ADMIN_MANAGE_TENANTS: "admin.manage_tenants",
  NPA_VIEW: "npa.view",
  AUDIT_VIEW: "audit.view",
  SETTINGS_VIEW: "settings.view"
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS: Permission[] = Object.values(PERMISSIONS);

export type Role =
  | "owner"
  | "ot_pb_head"
  | "ot_specialist"
  | "pb_engineer"
  | "ecologist"
  | "hr"
  | "lawyer"
  | "accountant"
  | "line_manager"
  | "worker"
  | "contractor_inspector"
  | "admin";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  owner: ALL_PERMISSIONS,
  admin: ALL_PERMISSIONS,
  ot_pb_head: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.PERSON_VIEW,
    PERMISSIONS.TEMPLATE_VIEW,
    PERMISSIONS.TEMPLATE_CREATE,
    PERMISSIONS.TEMPLATE_EDIT,
    PERMISSIONS.TEMPLATE_DELETE,
    PERMISSIONS.TEMPLATE_ACTIVATE,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_CREATE,
    PERMISSIONS.DOCUMENT_SIGN,
    PERMISSIONS.DOCUMENT_EXPORT,
    PERMISSIONS.RISK_VIEW,
    PERMISSIONS.RISK_ASSESS,
    PERMISSIONS.RISK_EDIT,
    PERMISSIONS.RISK_EXPORT,
    PERMISSIONS.PPE_VIEW,
    PERMISSIONS.PPE_ISSUE,
    PERMISSIONS.TRAINING_VIEW,
    PERMISSIONS.TRAINING_ASSIGN,
    PERMISSIONS.TRAINING_COMPLETE,
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.INCIDENT_VIEW,
    PERMISSIONS.INSPECTION_VIEW,
    PERMISSIONS.AUDIT_PREP_VIEW,
    PERMISSIONS.NPA_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.SETTINGS_VIEW
  ],
  ot_specialist: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.PERSON_VIEW,
    PERMISSIONS.TEMPLATE_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_CREATE,
    PERMISSIONS.DOCUMENT_EXPORT,
    PERMISSIONS.RISK_VIEW,
    PERMISSIONS.RISK_ASSESS,
    PERMISSIONS.RISK_EXPORT,
    PERMISSIONS.PPE_VIEW,
    PERMISSIONS.PPE_ISSUE,
    PERMISSIONS.TRAINING_VIEW,
    PERMISSIONS.TRAINING_ASSIGN,
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.INCIDENT_VIEW,
    PERMISSIONS.INSPECTION_VIEW,
    PERMISSIONS.AUDIT_PREP_VIEW,
    PERMISSIONS.NPA_VIEW
  ],
  pb_engineer: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_EXPORT,
    PERMISSIONS.FIRE_SAFETY_VIEW,
    PERMISSIONS.FIRE_TRAINING_VIEW,
    PERMISSIONS.FIRE_INSPECTIONS_VIEW,
    PERMISSIONS.INSPECTION_VIEW,
    PERMISSIONS.INCIDENT_VIEW,
    PERMISSIONS.AUDIT_PREP_VIEW
  ],
  ecologist: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_EXPORT,
    PERMISSIONS.RISK_VIEW,
    PERMISSIONS.RISK_EXPORT,
    PERMISSIONS.AUDIT_VIEW
  ],
  hr: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PERSON_VIEW,
    PERMISSIONS.TRAINING_VIEW,
    PERMISSIONS.TRAINING_ASSIGN,
    PERMISSIONS.TRAINING_COMPLETE
  ],
  lawyer: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.DOCUMENT_VIEW, PERMISSIONS.DOCUMENT_SIGN, PERMISSIONS.DOCUMENT_EXPORT],
  accountant: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.DOCUMENT_VIEW, PERMISSIONS.DOCUMENT_EXPORT],
  line_manager: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_EXPORT,
    PERMISSIONS.TRAINING_VIEW,
    PERMISSIONS.PPE_VIEW,
    PERMISSIONS.TASK_VIEW
  ],
  worker: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.DOCUMENT_VIEW, PERMISSIONS.TRAINING_VIEW],
  contractor_inspector: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.INSPECTION_VIEW,
    PERMISSIONS.FIRE_INSPECTIONS_VIEW,
    PERMISSIONS.CONTRACTOR_VIEW
  ]
};
