"""SEC-65 RLS coverage registry — the ratchet source of truth.

Two frozensets partition every tenant-scoped table (a table with a ``tenant_id``
column) into "has row-level security" vs "not yet". ``scripts/audit/check_rls_coverage.py``
enforces that partition: any tenant table absent from *both* sets fails the guard, so a
newly added tenant table forces a conscious choice — arm it with RLS (move it to
``RLS_ENABLED_TABLES`` alongside a migration) or record it in ``RLS_EXEMPT_TABLES``.

As RLS rolls out domain by domain, tables migrate from EXEMPT to ENABLED. The ``-m db``
test ``test_rls_enabled_matches_postgres`` cross-checks ENABLED against the live
PostgreSQL catalog so this registry cannot drift from what the migrations actually did.
"""

from __future__ import annotations

# Tables with FORCE ROW LEVEL SECURITY + the ``tenant_isolation`` policy (SEC-65).
# Keep in sync with the ``20260722_sec65_rls_*`` / ``20260723_sec65_rls_*`` migrations.
RLS_ENABLED_TABLES: frozenset[str] = frozenset(
    {
        "action_plan_items",
        "action_plans",
        "approval_decision_logs",
        "approval_decisions",
        "approval_instance_steps",
        "approval_instances",
        "approval_processes",
        "approval_requests",
        "approval_route_steps",
        "approval_routes",
        "approval_tasks",
        "asset",
        "attestation",
        "automation_rule",
        "automation_rule_trigger",
        "billing_events",
        "branch",
        "briefing_entries",
        "briefing_journals",
        "briefing_signatures",
        "briefing_templates",
        "budget_expense",
        "budget_expense_article",
        "budget_reimbursement",
        "budget_reimbursement_item",
        "calendar_events",
        "checklist",
        "client_portal_read_models",
        "client_portal_tokens",
        "client_request_tickets",
        "committee",
        "committee_agenda_item",
        "committee_decision",
        "committee_decision_task",
        "committee_decision_vote",
        "committee_meeting",
        "committee_meeting_attendance",
        "committee_member",
        "company",
        "compliance_deadlines",
        "contract",
        "contractor_document_requirement",
        "contractor_documents",
        "contractor_employees",
        "contractor_incidents",
        "contractor_readiness_read_models",
        "contractor_registry",
        "corrective_action_attachments",
        "corrective_actions",
        "correctiveaction",
        "dashboard_kpi_snapshots",
        "department",
        "document",
        "document_artifacts",
        "document_batch_item",
        "document_batch_run",
        "document_job_steps",
        "document_jobs",
        "document_pack",
        "document_pack_item",
        "document_snapshot",
        "documentgenerationjob",
        "documentversion",
        "edo_messages",
        "edo_receipts",
        "edo_status_events",
        "edo_status_history",
        "edo_webhook_inbox",
        "equipment",
        "file",
        "file_content_index",
        "file_download_logs",
        "file_links",
        "file_objects",
        "file_scan_results",
        "file_text_index",
        "file_versions",
        "files",
        "findings",
        "hazard_bindings",
        "hazard_measures",
        "hazards",
        "incident",
        "incident_attachments",
        "incident_cases",
        "incident_investigations",
        "incident_log",
        "incident_person",
        "incident_persons",
        "inspection",
        "inspection_attachments",
        "inspection_checklist_items",
        "inspection_checklists",
        "inspection_plan_items",
        "inspection_plans",
        "inspection_prep_gaps",
        "inspection_prep_items",
        "inspection_prep_packages",
        "inspection_prescription",
        "inspection_result",
        "inspection_run_items",
        "inspection_runs",
        "invoice",
        "invoices",
        "journal",
        "journalentry",
        "kpi_definitions",
        "medical_exam",
        "medical_factor",
        "medical_norm",
        "medical_referral",
        "medical_suspension",
        "notification_channel_settings",
        "notification_templates",
        "notifications",
        "npa",
        "npabinding",
        "ops_inspections",
        "ops_prescriptions",
        "order",
        "pack_run_items",
        "pack_run_logs",
        "pack_runs",
        "package_events",
        "package_preset_items",
        "package_presets",
        "package_presets_v2",
        "package_profiles",
        "package_profiles_v2",
        "package_read_models",
        "package_requirements",
        "package_runs",
        "packagepreset",
        "packageprofile",
        "pdn_access_log",
        "permit",
        "person",
        "person_compliance_read_models",
        "pipeline_profiles",
        "pipeline_runs",
        "pipeline_step_locks",
        "plan_tasks",
        "plantask",
        "portal_request_messages",
        "portal_requests",
        "position",
        "position_hazard",
        "ppe_inventory_count",
        "ppe_inventory_count_line",
        "ppe_safety_budget",
        "ppe_stock_batch",
        "ppe_stock_movement",
        "ppe_supplier",
        "ppeissue",
        "ppeitem",
        "ppenorm",
        "prescription_items",
        "psychiatric_activity_type",
        "psychiatric_position_activity",
        "regulatory_inspection",
        "reminder_rules",
        "risk",
        "risk_assessment_items",
        "risk_assessments",
        "risk_cards",
        "risk_controls",
        "risk_hazards",
        "risk_map_item_measures",
        "risk_map_items",
        "risk_maps",
        "risk_matrix",
        "risk_measures",
        "risk_methodologies",
        "riskmap",
        "riskmethodology",
        "safety_budget",
        "saved_calendar_views",
        "search_documents",
        "search_index_entries",
        "search_recent_queries",
        "search_saved_queries",
        "signature_requests",
        "site",
        "site_safety_read_models",
        "sout_campaign",
        "sout_class_history",
        "sout_factor",
        "sout_guarantee",
        "sout_workplace",
        "subscriptions",
        "task",
        "template",
        "templateusage",
        "templateversion",
        "tenant_counters",
        "tenant_integrations_keys",
        "tenant_limits_override",
        "tenant_quotas",
        "tenant_quotas_counters",
        "tenant_rate_limits",
        "tenant_settings",
        "training",
        "training_attempts",
        "training_certificates",
        "training_course",
        "training_enrollments",
        "training_groups",
        "training_lessons",
        "training_modules",
        "training_plan",
        "training_programs",
        "training_protocol_items",
        "training_protocols",
        "training_session",
        "training_test_questions",
        "training_tests",
        "usage_counters",
        "violation",
        "webhook_deliveries",
        "webhook_endpoints",
        "work_permit",
        "work_permit_briefing",
        "work_permit_daily_admission",
        "work_permit_event",
        "work_permit_member",
        "workflow_definition_versions",
        "workflow_definitions",
        "workflow_instances",
        "workflow_tasks",
        "workflow_timeline_events",
        "workplace",
        "workplace_hazard",
    }
)

# Tenant-scoped tables that do NOT yet have RLS. Ratchet snapshot, not a permanent
# exemption: shrink it (move names to RLS_ENABLED_TABLES) as coverage grows. Some entries
# are deliberately cautious:
#   * authz_*/api_key/api_tokens/refresh_session/user* — read on the hot auth/permission
#     path, need dedicated analysis before RLS.
#   * webhook_subscription — legitimately stores global rows with tenant_id IS NULL,
#     which the id-equality predicate would hide.
#   * outbox/outbox_events/idempotency_keys/inbound_webhook_dedup — cross-tenant infra
#     queues with their own consumers; separate analysis.
# A NEW tenant table must be added here (or to RLS_ENABLED_TABLES) or the coverage
# guard fails.
RLS_EXEMPT_TABLES: frozenset[str] = frozenset(
    {
        "api_key",
        "api_tokens",
        "audit_export_job",
        "auditlog",
        "authz_permissions",
        "authz_policies",
        "authz_role_permissions",
        "authz_roles",
        "authz_user_roles",
        "download_logs",
        "export_jobs",
        "export_schedules",
        "external_registry_jobs",
        "featureenablement",
        "header_footer_presets",
        "idempotency_keys",
        "inbound_webhook_dedup",
        "job_logs",
        "marketplace_catalog_items",
        "offline_media_queue",
        "offline_sync_batches",
        "outbox",
        "outbox_events",
        "pdf_conversion_runs",
        "refresh_session",
        "replace_map",
        "replace_run",
        "report_definition",
        "securityauditlog",
        "user",
        "user_attribute",
        "user_role",
        "webhook_subscription",
    }
)
