"""SEC-65 RLS coverage registry — the ratchet source of truth.

Two frozensets partition every tenant-scoped table (a table with a ``tenant_id``
column) into "has row-level security" vs "not yet". ``scripts/audit/check_rls_coverage.py``
enforces that partition: any tenant table absent from *both* sets fails the guard, so a
newly added tenant table forces a conscious choice — arm it with RLS (move it to
``RLS_ENABLED_TABLES`` alongside a migration) or record it in ``RLS_EXEMPT_TABLES``.

As RLS rolls out domain by domain, tables migrate from EXEMPT to ENABLED. The ``-m db``
test ``test_rls_enabled_matches_postgres`` cross-checks ENABLED against the live
PostgreSQL catalog so this registry cannot drift from what the migrations actually did.
"""

from __future__ import annotations

# Tables with FORCE ROW LEVEL SECURITY + the ``tenant_isolation`` policy (SEC-65).
# Keep in sync with the ``20260722_sec65_rls_*`` / ``20260723_sec65_rls_*`` migrations.
RLS_ENABLED_TABLES: frozenset[str] = frozenset(
    {
        "action_plan_items",
        "action_plans",
        "api_key",
        "api_tokens",
        "approval_decision_logs",
        "approval_decisions",
        "approval_instance_steps",
        "approval_instances",
        "approval_processes",
        "approval_requests",
        "approval_route_steps",
        "approval_routes",
        "approval_tasks",
        "asset",
        "attestation",
        "audit_export_job",
        "auditlog",
        "authz_policies",
        "authz_role_permissions",
        "authz_roles",
        "authz_user_roles",
        "automation_rule",
        "automation_rule_trigger",
        "billing_events",
        "branch",
        "briefing_entries",
        "briefing_journals",
        "briefing_signatures",
        "briefing_templates",
        "budget_expense",
        "budget_expense_article",
        "budget_reimbursement",
        "budget_reimbursement_item",
        "calendar_events",
        "checklist",
        "client_audit_report",
        "client_change",
        "client_portal_read_models",
        "client_portal_tokens",
        "client_request_tickets",
        "committee",
        "committee_agenda_item",
        "committee_decision",
        "committee_decision_task",
        "committee_decision_vote",
        "committee_meeting",
        "committee_meeting_attendance",
        "committee_meeting_invitation",
        "fire_document",
        "hazardous_facility",
        "nvos_facility",
        "opo_device_work",
        "opo_production_control_measure",
        "opo_production_control_plan",
        "opo_technical_device",
        "fire_drill",
        "fire_maintenance",
        "fire_safety_equipment",
        "committee_member",
        "companies",
        "company",
        "compliance_deadlines",
        "contract",
        "contractor_document_requirement",
        "contractor_documents",
        "contractor_employees",
        "contractor_incidents",
        "contractor_readiness_read_models",
        "contractor_registry",
        "corrective_action_attachments",
        "corrective_actions",
        "correctiveaction",
        "dashboard_kpi_snapshots",
        "department",
        "departments",
        "document",
        "document_artifacts",
        "document_batch_item",
        "document_batch_run",
        "document_job_steps",
        "document_jobs",
        "document_pack",
        "document_pack_item",
        "document_snapshot",
        "documentgenerationjob",
        "documentversion",
        "download_logs",
        "edo_messages",
        "edo_receipts",
        "edo_status_events",
        "edo_status_history",
        "edo_webhook_inbox",
        "equipment",
        "export_jobs",
        "export_schedules",
        "external_registry_jobs",
        "featureenablement",
        "file",
        "file_content_index",
        "file_download_logs",
        "file_links",
        "file_objects",
        "file_scan_results",
        "file_text_index",
        "file_versions",
        "files",
        "findings",
        "hazard_bindings",
        "hazard_measures",
        "hazards",
        "header_footer_presets",
        "idempotency_keys",
        "import_batch",
        "import_row",
        "inbound_webhook_dedup",
        "incident",
        "incident_attachments",
        "incident_cases",
        "incident_investigations",
        "incident_log",
        "incident_person",
        "incident_persons",
        "inspection",
        "inspection_attachments",
        "inspection_checklist_items",
        "inspection_checklists",
        "inspection_plan_items",
        "inspection_plans",
        "inspection_prep_gaps",
        "inspection_prep_items",
        "inspection_prep_packages",
        "inspection_prescription",
        "inspection_result",
        "inspection_run_items",
        "inspection_runs",
        "invoice",
        "invoices",
        "job_logs",
        "journal",
        "journalentry",
        "kpi_definitions",
        "managed_client",
        "managed_client_access",
        "managed_client_consent",
        "managed_client_context_session",
        "managed_client_transfer",
        "marketplace_catalog_items",
        "medical_exam",
        "medical_factor",
        "medical_norm",
        "medical_referral",
        "medical_suspension",
        "notification_channel_settings",
        "notification_templates",
        "notifications",
        "npa",
        "npabinding",
        "offline_media_queue",
        "offline_sync_batches",
        "ops_inspections",
        "ops_prescriptions",
        "order",
        "outbox",
        "outbox_events",
        "pack_run_items",
        "pack_run_logs",
        "pack_runs",
        "package_events",
        "package_preset_items",
        "package_presets",
        "package_presets_v2",
        "package_profiles",
        "package_profiles_v2",
        "package_read_models",
        "package_requirements",
        "package_runs",
        "packagepreset",
        "packageprofile",
        "pdf_conversion_runs",
        "pdn_access_log",
        "pdn_consent",
        "pdn_erasure_record",
        "pdn_processing_activity",
        "pdn_processing_agreement",
        "permit",
        "person",
        "person_compliance_read_models",
        "persons",
        "pipeline_profiles",
        "pipeline_runs",
        "pipeline_step_locks",
        "plan_tasks",
        "plantask",
        "portal_request_messages",
        "portal_requests",
        "position",
        "position_hazard",
        "positions",
        "ppe_inventory_count",
        "ppe_inventory_count_line",
        "ppe_safety_budget",
        "ppe_stock_batch",
        "ppe_stock_movement",
        "ppe_supplier",
        "ppeissue",
        "ppeitem",
        "ppenorm",
        "prescription_items",
        "psychiatric_activity_type",
        "psychiatric_position_activity",
        "refresh_session",
        "regulatory_inspection",
        "reminder_rules",
        "replace_map",
        "replace_run",
        "report_definition",
        "risk",
        "risk_assessment_items",
        "risk_assessments",
        "risk_cards",
        "risk_controls",
        "risk_hazards",
        "risk_map_item_measures",
        "risk_map_items",
        "risk_maps",
        "risk_matrix",
        "risk_measures",
        "risk_methodologies",
        "riskmap",
        "riskmethodology",
        "safety_budget",
        "saved_calendar_views",
        "search_documents",
        "search_index_entries",
        "search_recent_queries",
        "search_saved_queries",
        "securityauditlog",
        "signature_requests",
        "site",
        "site_safety_read_models",
        "sites",
        "sout_campaign",
        "sout_class_history",
        "sout_factor",
        "sout_guarantee",
        "sout_workplace",
        "subscriptions",
        "task",
        "template",
        "templateusage",
        "templateversion",
        "tenant_branding",
        "tenant_counters",
        "tenant_legal_acceptance",
        "tenant_legal_document",
        "tenant_integrations_keys",
        "tenant_limits_override",
        "tenant_offboarding",
        "tenant_quotas",
        "tenant_quotas_counters",
        "tenant_rate_limits",
        "tenant_settings",
        "training",
        "training_attempts",
        "training_certificates",
        "training_course",
        "training_enrollments",
        "training_groups",
        "training_lessons",
        "training_modules",
        "training_plan",
        "training_plan_items",
        "training_plans",
        "training_programs",
        "training_protocol_items",
        "training_protocols",
        "training_session",
        "training_test_questions",
        "training_tests",
        "usage_counters",
        "user",
        "user_attribute",
        "user_role",
        "violation",
        "webhook_deliveries",
        "webhook_endpoints",
        "webhook_subscription",
        "work_permit",
        "work_permit_briefing",
        "work_permit_daily_admission",
        "work_permit_event",
        "work_permit_member",
        "workflow_definition_versions",
        "workflow_definitions",
        "workflow_instances",
        "workflow_tasks",
        "workflow_timeline_events",
        "workplace",
        "workplace_hazard",
        "workplaces",
    }
)

# Tenant-scoped tables deliberately left without RLS. The rollout is complete, so this
# is no longer a ratchet snapshot — it is a single, argued exception. A NEW tenant table
# must still be added here (or to RLS_ENABLED_TABLES) or the coverage guard fails.
#
#   * authz_permissions — a platform-wide permission dictionary, not tenant data. Rows are
#     derived from the static RESOURCE_PERMISSIONS map in code and are deliberately shared:
#     ``services/authz_seed.py`` looks a permission up by ``code`` ALONE and reuses whatever
#     row exists, so every catalogue row is physically owned by whichever tenant seeded
#     first. Its global UNIQUE(code) and uq_authz_permission_resource_action are enforced
#     ABOVE row security, so an id-equality predicate would hide the catalogue from every
#     other tenant while the unique index still rejected their INSERT — seeding a second
#     tenant would die on duplicate key. No tenant path reads it: the auth gate builds its
#     subject from JWT claims plus the static ROLE_PERMISSIONS dict, and
#     ``authz_role_permissions.permission_code`` is self-sufficient, so no join reaches
#     this table. Leaving it readable also keeps the
#     ``authz_role_permissions.permission_id`` FK valid, since it points at rows owned by
#     whichever tenant seeded first. Arming it would require making the catalogue
#     per-tenant (drop both global uniques, add UNIQUE(tenant_id, code) and
#     UNIQUE(tenant_id, resource, action), duplicate rows per tenant, recompute
#     permission_id) — a data-model change, out of SEC-65 scope. Leak risk is nil: the rows
#     are resource:action pairs identical for every tenant and fully derivable from code.
#
# Rejected alternative, for the record: extending the policy predicate with
# "OR tenant_id IS NULL" for this or any other table. A symmetric WITH CHECK would then let
# any tenant session create a globally-visible row — e.g. a webhook subscription that
# intercepts every tenant's events. All 264 policies keep the identical predicate.
RLS_EXEMPT_TABLES: frozenset[str] = frozenset(
    {
        "authz_permissions",
    }
)

# Armed tables that have NO ORM model, so SQLAlchemy metadata cannot see them.
#
# ``check_rls_coverage.py`` builds its denominator from the ORM, which means a table with
# a ``tenant_id`` column but no model is invisible to it — it never enters the count and
# can stay unarmed forever (this is how ``webhook_subscriptions`` hid). The live-schema
# audit ``scripts/audit/check_rls_live_schema.py`` reads ``pg_attribute`` instead and
# found these eight; ``20260728_sec65_rls_model_less_tables`` arms them.
#
# They are PLURAL duplicates of armed singular tables, created by migrations that were
# never matched with models: ``20260401_next58_safety_core`` (org registry) and
# ``20260317_next46_training_briefings_offline`` (training plans). Listing them here is
# what lets the metadata guard treat them as legitimate registry entries instead of stale
# names. Whether the duplicates should exist at all is a data-model cleanup of its own.
RLS_MODEL_LESS_TABLES: frozenset[str] = frozenset(
    {
        "companies",
        "departments",
        "persons",
        "positions",
        "sites",
        "training_plan_items",
        "training_plans",
        "workplaces",
    }
)
